---
# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0
# https://kind.sigs.k8s.io/docs/user/configuration/
# Kubernetes 1.37: v1beta1 Workload/PodGroup and v1alpha3 CompositePodGroup APIs.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  DRAExtendedResource: true
  DRAResourceClaimDeviceStatus: true
  DRAConsumableCapacity: true
  GenericWorkload: true
  WorkloadWithJob: true
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri"]
      enable_cdi = true
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        controllerManager:
          extraArgs:
            v: "6"
            feature-gates: "GenericWorkload=true,WorkloadWithJob=true,CompositePodGroup=true,TopologyAwareWorkloadScheduling=true"
        scheduler:
          extraArgs:
            v: "5"
            vmodule: "allocator=6,dynamicresources=6"
            feature-gates: "GenericWorkload=true,WorkloadWithJob=true"
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            runtime-config: "scheduling.k8s.io/v1beta1=true,scheduling.k8s.io/v1alpha3=true"
            feature-gates: "GenericWorkload=true,WorkloadWithJob=true,CompositePodGroup=true,TopologyAwareWorkloadScheduling=true"
  - role: worker
  - role: worker
  - role: worker
  - role: worker
    labels:
      scheduler.slinky.slurm.net/slurm-bridge: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            register-with-taints: "slinky.slurm.net/managed-node=slurm-bridge-scheduler:NoExecute"
  - role: worker
    labels:
      scheduler.slinky.slurm.net/slurm-bridge: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            register-with-taints: "slinky.slurm.net/managed-node=slurm-bridge-scheduler:NoExecute"
  - role: worker
    labels:
      scheduler.slinky.slurm.net/slurm-bridge: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            register-with-taints: "slinky.slurm.net/managed-node=slurm-bridge-scheduler:NoExecute"
  - role: worker
    labels:
      scheduler.slinky.slurm.net/slurm-bridge: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            register-with-taints: "slinky.slurm.net/managed-node=slurm-bridge-scheduler:NoExecute"
  - role: worker
    labels:
      scheduler.slinky.slurm.net/slurm-bridge: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            register-with-taints: "slinky.slurm.net/managed-node=slurm-bridge-scheduler:NoExecute"
  - role: worker
    labels:
      scheduler.slinky.slurm.net/slurm-bridge: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            register-with-taints: "slinky.slurm.net/managed-node=slurm-bridge-scheduler:NoExecute"
